apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: nodeinfo
  namespace: openfaas-fn
spec:
  name: nodeinfo
  handler: node main.js
  image: functions/nodeinfo:latest
  # limits:
  #   memory: 1000Mi
  #   cpu: 2000m
  requests:
    # memory: 10Gi
    cpu: "4"
  # labels:
  #   com.openfaas.scale.min: "0"
  constraints: 
    -  "node-use=serving"
