apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mlflows.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: MLFlow
    plural: mlflows
    singular: mlflow
    shortNames:
      - flows
      - flow
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true