apiVersion: apps/v1
kind: Deployment
metadata:
  name: resident-lstm-pipeline
spec:
  selector:
    matchLabels:
      app: resident-lstm-pipeline
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: resident-lstm-pipeline
    spec:
      containers:
      - name: resident-lstm-pipeline
        image: james759426/resident-lstm-pipeline:0.0.1
      nodeSelector:
        node-use: "serving"