apiVersion: kopf.dev/v1
kind: MLFlow
metadata:
  name: lstm-pipeline-4
  namespace: ml-faas
spec:
  pipeline:
    stage1:
      name: data-preprocess
      rule: ['dev', 'user']
      node: training
      step:
      - name: load-data
        mlfun: james759426/lstm-load-data:0.0.1
        # limits:
        #   memory: 100Mi
        #   cpu: 100m
        requests:
          # memory: 50Mi
          cpu: "1000m"
        # scale-fun:   
        #   cpu-percent: 50
        #   scale-fun-max: 5
      - name: time-parser
        mlfun: james759426/lstm-time-parser:0.0.1
        # limits:
        #   memory: 100Mi
        #   cpu: 100m
        requests:
          # memory: 50Mi
          cpu: "2000m"
      - name: data-clean
        mlfun: james759426/lstm-data-clean:0.0.1
        # limits:
        #   memory: 100Mi
        #   cpu: 100m
        requests:
        #   memory: 50Mi
          cpu: "2000m"
    stage2:
      name: LSTM-model-build
      rule: ['dev']
      node: training
      step:
      - name: train-data-build
        mlfun: james759426/lstm-train-data-build:0.0.1
        # limits:
        #   memory: 100Mi
        #   cpu: 200m
        requests:
        #   memory: 50Mi
          cpu: "4000m"
      - name: train-model-build
        mlfun: james759426/lstm-train-model-build:0.0.1
        # limits:
        #   memory: 100Mi
        #   cpu: 200m
        requests:
        #   memory: 50Mi
          cpu: "1000m"
      - name: train-model
        mlfun: james759426/lstm-train-model-80:0.0.1
        # limits:
        #   memory: 100Mi
        #   cpu: 200m
        requests:
        #   memory: 50Mi
          cpu: "12000m"
    stage3:
      name: model-serving
      rule: ['dev', 'user']
      node: serving
      step:
      - name: model-serving-fun
        mlfun: james759426/lstm-model-serving-fun:0.0.1
        # limits:
        #   memory: 100Mi
        #   cpu: 200m
        requests:
          # memory: 50Mi
          cpu: "6000m"
    # stage4:
    #   name: data-visualization
    #   rule: ['dev', 'user']
    #   node: serving
    #   step:
    #   - name: data-visualization-fun
    #     mlfun: james759426/data-visualization-fun:0.0.1
    #     limits:
    #       memory: 100Mi
    #       cpu: 200m
    #     requests:
    #       memory: 50Mi
    #       cpu: 100m