version: 1.0
provider:
  name: openfaas
  gateway: http://10.20.1.54:31112
functions:
  # train-data-build:
  #   lang: python3
  #   handler: ./train-data-build
  #   image: james759426/random-forest-train-data-build:0.0.1
  #   environment:
  #     read_timeout: "60s"
  #     write_timeout: "60s"
  #     exec_timeout: "60s"
  
  train-model-build:
    lang: python3
    handler: ./train-model-build
    image: james759426/random-forest-train-model-build:0.0.1
    environment:
      read_timeout: "60s"
      write_timeout: "60s"
      exec_timeout: "60s"

  # train-model:
  #   lang: python3
  #   handler: ./train-model
  #   image: james759426/random-forest-train-model:0.0.1
  #   environment:
  #     read_timeout: "21600s"
  #     write_timeout: "21600s"
  #     exec_timeout: "21600s"