version: 1.0
provider:
  name: openfaas
  gateway: http://10.20.1.54:31112
functions:
  # train-data-build:
  #   lang: python3
  #   handler: ./train-data-build
  #   image: james759426/train-data-build:0.0.1

  # train-model-build:
  #   lang: python3
  #   handler: ./train-model-build
  #   image: james759426/train-model-build:0.0.1

  # train-model:
  #   lang: python3
  #   handler: ./train-model
  #   image: james759426/train-model:0.0.1

